apiVersion: v1
kind: Service
metadata:
  name: store-customer-ws-service
spec:
  selector:
    app: store-customer-ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3020
  type: NodePort
